skip_untracked = false
from_latest_tag = false
ignore_merge_commits = true
generate_mono_repository_global_tag = true

branch_whitelist = [
  "main",
  "release/**"
]

pre_bump_hooks = [
    "cargo build --release",
    "echo 'bumping from {{latest}} to {{version}}'",   
    "cargo set-version {{version}}"
]

post_bump_hooks = []

pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
