# pip install mkdocs pygments mkdocs-material pymdown-extensions mkdocs-material-extensions

site_name: Cerebro
site_author: Eike Steinig
site_description: Metagenomics and -transcriptomics platform for diagnosis of central nervous system infections
copyright: "Copyright © 2023-2025 Eike Steinig. All rights reserved."

site_url: https://esteinig.github.io/cerebro
repo_url: https://github.com/esteinig/cerebro

theme:
  name: material
  favicon: assets/mgp-logo-blue.png
  # logo: assets/mgp-logo-blue-white.png
  palette:
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Introduction': 'index.md'
  - 'Setup': 'setup.md'
  - 'Pipeline': 'pipeline.md'
  - 'Deployment': 'deployment.md'
  - 'Interface': 'interface.md'
  - 'Reports': 'reports.md'
  - 'Security': 'security.md'
  - 'Tutorials': 'security.md'
  - 'Schematics': 'security.md'
  - 'Changelog': 'changelog.md'