file                        = "report.hbs"                       # if path does not start with '/' it is relative to this file 
logo                        = "logo.png"                         # if path does not start with '/' it is relative to this file
name                        = "cerebro-report-v1.0"
version                     = "1.0.0"
description                 = "LaTeX template for Cerebro Report"

# Legal section of template

[legal]
disclosure                  = """
This report overrides all previous reports. The results relate solely to the sample/s as received and are limited to the specific tests undertaken as listed on the report. The results of this report are confidential
and are not to be used or disclosed to any other person or used for any other purpose, whether directly or indirectly, unless that use is disclosed or the purpose is expressly authorised in writing by
the Victorian Infectious Diseases Reference Laboratory (VIDRL) and the named recipient on this report. 
"""
liability                   = """
To the fullest extent permitted by law, VIDRL will not be liable for any loss or claim (including legal costs calculated on an indemnity
basis) which arise because of (a) problems related to the merchantability, fitness or quality of the sample/s, or (b) any negligent or unlawful act or omissions by VIDRL that is connected with any
activities or services provided by VIDRL under this agreement (including the timing and/or method under which the sample/s were taken, stored or transported)
"""
disclaimer                  = """
This metagenomics assay is a research-only assay, under ongoing development, and 
should only be used in addition to usual diagnostic testing algorithms. The test has been performed using an
unapproved IVD medical device that has not been evaluated for quality, safety or performance by the
Therapeutic Goods Administration. Results are not sufficient to rule in or out causative pathogens, and 
should not be used as the basis for clinical management decisions. Methods used for this analysis have 
not yet been validated according to the current NPAAC standards and results should be interpreted accordingly.
NATA/RCPA accreditation does not cover the performance of this service.
"""

# Authorisation section

[authorisation]
issuing_laboratory_text     = "Issued by the Victorian Infectious Diseases Reference Laboratory (VIDRL), 792 Elizabeth St, Melbourne VIC 3004." 
report_identifier_text      = "Report identifier for the MetaGP project: "

# report_identifier           = ""

[[authorisation.signature]]
name                        = "Dr. Chuan Lim"
position                    = "Acting Director"
institution                 = "VIDRL"


[[authorisation.signature]]
name                        = "Dr. Prashanth Ramachandran"
position                    = "Neurologist"
institution                 = "Williamson Research Group"